preprocessing:
  performance_curve: "data/Leistungskurve_data.xlsx"
  smoothing_window: 5
  interpolation_points: 500

generator:
  a: 17.192       # Kennlinienparameter
  b: -182.54

tsr_scan:
  lambda_min:  6.0
  lambda_max:  8.0
  lambda_step: 0.25
  R:           0.5       # m
  rho:         1.225     # kg/m³

bem:
  r_min:        0.5     # m
  r_max:        0.6      # m
  N_segments:   30
  tol_induction: 1e-4
  B:            3        # Blattzahl

profile_selection:
  mu_air:       1.8e-5    # Pa·s
  score_weights:
    ld:     0.7
    clmax:  0.3
  profile_folder: "data/AirFoil_datenbank"

output:
  design_params: "results/design_params.json"
  tsr_scan:      "results/tsr_scan.json"
  bem:           "results/bem_results.json"
  profiles:      "results/profile_map.json"